#!/bin/bash

srun -p TitanX --gres=gpu --chdir=/media/hpc2_storage/ibulygin/learnable-triangulation-pytorch \
python3.6 train_fr.py \
--logdir=../logs/feature_regressor \
--config=./experiments/human36m/train/human36m_temporal_fr.yaml \
--experiment_comment="h36_sv_dist_fr-only_dt-4_dil-100_bs-5-5_C-2_lr-1e-3"
