#!/bin/bash

# srun -p TitanBlack --gres=gpu --chdir=/media/hpc2_storage/ibulygin/learnable-triangulation-pytorch -w ws-04 \
#srun -p TitanX --gres=gpu --chdir=/media/hpc2_storage/ibulygin/learnable-triangulation-pytorch -w hpc2 \
#srun -p TitanBlack --gres=gpu --chdir=/media/hpc2_storage/ibulygin/learnable-triangulation-pytorch -w ws-03 \
srun -p TitanBlack --gres=gpu --chdir=/media/hpc2_storage/ibulygin/learnable-triangulation-pytorch -w ws-05 \
python3.6 train_fr.py \
--logdir=../logs/feature_regressor \
--config=./experiments/human36m/train/human36m_fr.yaml \
--experiment_comment="h36_sv64_dist_fr-only_dt-3_dil-5_bs-5-5_C-2_lr-1e-3"
